### ISSUE TITLE
ValidationError: 'sample' is a required property

### ISSUE THREAD

**Issue by vaskaxxx** [jaleezyy/covid-19-signal#119]
When running:
snakemake -kp --configfile config.yaml --cores=2 --use-conda --conda-prefix=$PWD/.snakemake/conda all
I receive 
ValidationError: 'sample' is a required property
The sample_table.csv definitely contains sample column values, yet the error still occurs. 
Have any one encountered this error?

**Comment by fmaguire** [comment]
That's an unusual issue as it is just reading the sample table with pandas `pd.read_csv` than validating it against a simple 3 column schema. 

Is your sample table definitely using commands instead of tabs to delineate the fields/columns?

Can you share a copy or a subset of your sample table that still causes the error?

**Comment by vaskaxxx** [comment]
Turns out it was a wrong separator in csv (it should be a comma). The problem is fixed. Thanks.
